import { MetricCard } from "@/components/metric-card";
import { PredictionChart } from "@/components/prediction-chart";
import { Refresh } from "@/components/refresh";
import { getDashboardData,snapshotURL } from "@/lib/dashboard-data";
export const dynamic="force-dynamic";
const date=(v?:string|null)=>v?new Intl.DateTimeFormat("es-CO",{dateStyle:"medium",timeStyle:"short",timeZone:"America/Bogota"}).format(new Date(v)):"Sin registro";
const num=(v?:number|null,d=1)=>v==null?"—":new Intl.NumberFormat("es-CO",{maximumFractionDigits:d}).format(v);
const labels:Record<string,string>={stable:"Sin señal de drift",warning:"Señal moderada",high:"Señal fuerte",insufficient_data:"Datos insuficientes"};
export default async function Page(){
 const d=await getDashboardData();
 const stale=d?.stale??false;
 const affected=d?.drift.stations.filter(s=>s.status==="high"||s.status==="warning").length??0;
 return <main>
 <header className="hero"><nav><div className="brand-mark">PT</div><div><b>Pulso TransMi</b><span>Equipo Nao</span></div><a className="nav-link" href="https://github.com/naomiv2910-cell/pulso-transmi-equipo-nao/actions" target="_blank" rel="noreferrer">Ver ejecuciones ↗</a></nav>
 <div className="hero-grid"><div><p className="kicker">Observatorio del modelo · MLOps</p><h1>El pulso de<br/><em>tus predicciones.</em></h1><p className="hero-copy">Demanda, drift y precisión. Una lectura de los datos que están llegando y de las predicciones que sí entregaste.</p></div><div className="hero-status"><span>ESTADO DEL INFORME</span><strong>{!d?"Sin datos disponibles":stale?"Revisar actualización":"Informe actualizado"}</strong><p>{d?date(d.generated_at):"No se pudo leer el último informe."}</p><Refresh/></div></div>
 </header>
 <section className="content">{!d?<article className="panel"><h2>El informe no está disponible</h2><p>Puede haber una actualización en curso o un error de conexión. No mostramos métricas estimadas ni datos de demostración.</p><a href="https://github.com/naomiv2910-cell/pulso-transmi-equipo-nao/actions/workflows/analytics.yml">Consultar el cálculo de drift ↗</a></article>:<>
 {stale&&<p className="notice">Este informe tiene más de dos horas. Los valores corresponden a la fecha indicada, no al estado actual.</p>}
 <div className="section-heading"><div><p className="kicker dark">Última lectura</p><h2>Lo que dicen los datos</h2></div><p>Horas locales: Bogotá · Ventanas del modelo: tiempo virtual</p></div>
 <div className="metrics-grid">
 <MetricCard eyebrow="Drift de demanda" value={labels[d.drift.status]??d.drift.status} detail={`${affected} de ${d.drift.stations.length} estaciones con señal`} accent="coral"/>
 <MetricCard eyebrow="Accuracy de entregas evaluadas" value={d.performance.accuracy===null?"—":`${num(d.performance.accuracy)} %`} detail="Últimas 24 h virtuales · sin ausencias"/>
 <MetricCard eyebrow="Ciclos evaluados en la ventana" value={String(d.performance.evaluated_cycles)} detail={`${d.performance.samples} predicciones con verdad completa`} accent="navy"/>
 <MetricCard eyebrow="WAPE de entregas evaluadas" value={d.performance.wape===null?"—":`${num(d.performance.wape*100)} %`} detail="Error relativo · promedio por estación"/>
 </div>
 <div className="ground-truth"><div className="ground-icon" aria-hidden="true">i</div><div><h3>Esta precisión no es tu posición en el ranking</h3><p>Se evalúan únicamente ciclos entregados con demanda real completa. El tablero oficial también penaliza las ausencias. Los períodos sin datos no se reemplazan por ceros aquí.</p></div></div>
 <article className="panel drift-panel"><div className="panel-title"><div><p className="kicker dark">¿Cambió la demanda?</p><h2>Drift por estación</h2></div><span className={`signal signal-${d.drift.status}`}>{labels[d.drift.status]}</span></div>
 <p className="explanation">Comparamos las últimas 24 horas virtuales con el entrenamiento, ajustando por estación, día de semana y hora. El PSI mide el cambio en la distribución de esos residuos.</p>
 <div className="periods"><div><span>Referencia de entrenamiento</span><strong>{date(d.drift.reference_start)} — {date(d.drift.reference_end)}</strong></div><div><span>Ventana reciente · reloj virtual</span><strong>{date(d.drift.window_start)} — {date(d.drift.window_end)}</strong></div></div>
 <div className="table-scroll"><table><caption className="sr-only">PSI y cambio estandarizado de demanda por estación</caption><thead><tr><th>Estación</th><th>PSI</th><th>Cambio de media¹</th><th>Muestras recientes</th><th>Señal</th></tr></thead><tbody>{d.drift.stations.map(s=><tr key={s.station_id}><td><strong>{s.name}</strong><small>{s.station_id}</small></td><td><div className="psi-value">{num(s.psi,3)}<span className="psi-track"><i style={{width:`${Math.min((s.psi??0)/.5*100,100)}%`}}/></span></div></td><td>{num(s.mean_shift,3)}</td><td>{s.recent_samples} / 96</td><td><span className={`signal signal-${s.status}`}>{labels[s.status]}</span></td></tr>)}</tbody></table></div>
 <p className="method-note">PSI ≥ 0,20: señal moderada; ≥ 0,30: fuerte. ¹ Cambio de media en desviaciones estándar: ≥ 0,5 moderado; ≥ 1 fuerte. Son umbrales heurísticos, no una prueba causal de concept drift. Se requieren 28 días de referencia y 96 observaciones recientes por estación.</p>
 </article>
 <div className="two-column"><article className="panel"><div className="panel-title"><div><p className="kicker dark">Precisión observada</p><h2>Últimos ciclos evaluados</h2></div></div>{d.performance.history.length?<div className="history">{d.performance.history.slice(-8).map(h=><div className="history-row" key={h.cycle_id}><span>{date(h.target_end)}<small>Fin del pronóstico · virtual</small></span><div className="accuracy-track"><i style={{width:`${h.accuracy}%`}}/></div><strong>{num(h.accuracy)} %</strong></div>)}</div>:<p className="explanation">Todavía no hay ciclos completos evaluables en la ventana. Esperamos la demanda real publicada por la API.</p>}<p className="method-note">{d.performance.pending_cycles} ciclos pendientes de verdad completa. MAE: {num(d.performance.mae)} pasajeros.</p></article>
 <article className="panel model-panel"><p className="kicker dark">Modelo en producción</p><h2>{d.model.version}</h2><div className="model-name"><strong>Gradient Boosting</strong><span>{d.model.algorithm}</span></div><div className="detail-grid"><div><span>Horizontes</span><strong>15 · 30 · 45 · 60 min</strong></div><div><span>Entrenado hasta</span><strong>{date(d.model.training_end)}</strong></div></div><p className="explanation">{d.recommendation}</p></article></div>
 <article className="panel chart-panel"><div className="panel-title"><div><p className="kicker dark">Continuidad de envíos</p><h2>Último pronóstico guardado</h2></div><span className="signal signal-stable">{d.deliveries.latest_predictions.length} predicciones</span></div><p className="submission-id">{d.deliveries.latest_cycle??"Sin entregas"}</p><p className="explanation">Enviado: {date(d.deliveries.latest_submitted_at)} · {d.deliveries.stored_cycles} ciclos guardados en total.</p><PredictionChart predictions={d.deliveries.latest_predictions}/></article>
 <div className="ground-truth"><div className="ground-icon" aria-hidden="true">↻</div><div><h3>Datos trazables, sin intervenir en los envíos</h3><p>{num(d.observations.count,0)} observaciones almacenadas. Último dato virtual: {date(d.observations.last_at)}. El informe se recalcula al renovar la vigilancia, aproximadamente cada 45 minutos. Esta página consulta el informe cada minuto.</p></div></div>
 <details className="methodology"><summary>Cómo interpretar el drift y las métricas</summary><p>El drift describe un cambio en la distribución de la demanda. Una señal fuerte no demuestra por sí sola que el modelo haya dejado de funcionar. Contrasta el cambio con el error en los ciclos entregados y con suficientes datos nuevos antes de reentrenar.</p><p>Accuracy = promedio por estación de 100 × max(0, 1 − WAPE). Cada ciclo debe tener verdad publicada para todos sus targets almacenados antes de evaluarse. Los promedios de la ventana se recalculan sobre las predicciones, no promediando porcentajes de ciclos.</p><a href={snapshotURL} target="_blank" rel="noreferrer">Descargar informe JSON ↗</a></details>
 </>}</section><footer><span>Pulso TransMi · Equipo Nao</span><span>Monitoreo de solo lectura · datos sintéticos del reto académico</span></footer>
 </main>;
}
