-- Esquema inicial de Pulso TransMi.
-- Las tablas quedan protegidas por RLS y sin acceso directo para anon/authenticated.

create table public.dataset_snapshots (
  id uuid primary key default gen_random_uuid(),
  dataset_name text not null,
  generated_at date not null,
  history_start timestamptz not null,
  history_end timestamptz not null,
  frequency_minutes smallint not null check (frequency_minutes > 0),
  station_count integer not null check (station_count >= 0),
  observation_rows integer not null check (observation_rows >= 0),
  context_rows integer not null check (context_rows >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (dataset_name, generated_at)
);

create table public.stations (
  station_id text primary key check (station_id ~ '^[0-9]+$'),
  station_name text not null,
  corridor text not null,
  latitude double precision not null check (latitude between -90 and 90),
  longitude double precision not null check (longitude between -180 and 180),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.observations (
  station_id text not null references public.stations(station_id) on update cascade,
  observed_at timestamptz not null,
  demand integer not null check (demand >= 0),
  snapshot_id uuid references public.dataset_snapshots(id) on delete set null,
  ingested_at timestamptz not null default now(),
  primary key (station_id, observed_at)
);

create table public.context_observations (
  observed_at timestamptz primary key,
  rain_mm double precision not null check (rain_mm >= 0),
  rain_forecast double precision,
  temperature_c double precision not null,
  temperature_forecast double precision,
  event_intensity double precision not null check (event_intensity between 0 and 1),
  snapshot_id uuid references public.dataset_snapshots(id) on delete set null,
  ingested_at timestamptz not null default now()
);

create table public.pipeline_runs (
  id uuid primary key default gen_random_uuid(),
  run_type text not null check (run_type in ('ingest', 'train', 'predict', 'evaluate', 'monitor')),
  status text not null check (status in ('running', 'succeeded', 'failed', 'skipped')),
  cutoff_at timestamptz,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  rows_processed integer not null default 0 check (rows_processed >= 0),
  commit_sha text,
  details jsonb not null default '{}'::jsonb,
  error_message text,
  check (finished_at is null or finished_at >= started_at)
);

create table public.model_versions (
  id uuid primary key default gen_random_uuid(),
  model_name text not null,
  version text not null,
  algorithm text not null,
  training_start timestamptz not null,
  training_end timestamptz not null,
  features jsonb not null default '[]'::jsonb,
  parameters jsonb not null default '{}'::jsonb,
  validation_metrics jsonb not null default '{}'::jsonb,
  artifact_uri text,
  commit_sha text,
  is_champion boolean not null default false,
  created_at timestamptz not null default now(),
  unique (model_name, version),
  check (training_end >= training_start)
);

create unique index one_champion_per_model
  on public.model_versions (model_name)
  where is_champion;

create table public.forecast_cycles (
  id uuid primary key default gen_random_uuid(),
  external_cycle_id text unique,
  status text not null check (status in ('open', 'submitted', 'closed', 'cancelled')),
  issued_at timestamptz not null,
  target_start timestamptz not null,
  target_end timestamptz not null,
  closes_at timestamptz,
  created_at timestamptz not null default now(),
  check (target_end >= target_start)
);

create table public.predictions (
  id bigint generated by default as identity primary key,
  cycle_id uuid not null references public.forecast_cycles(id) on delete cascade,
  model_id uuid not null references public.model_versions(id),
  station_id text not null references public.stations(station_id),
  target_at timestamptz not null,
  horizon_minutes smallint not null check (horizon_minutes > 0),
  predicted_demand double precision not null check (predicted_demand >= 0),
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  unique (cycle_id, model_id, station_id, target_at)
);

create table public.evaluation_metrics (
  id bigint generated by default as identity primary key,
  cycle_id uuid references public.forecast_cycles(id) on delete cascade,
  model_id uuid not null references public.model_versions(id),
  station_id text references public.stations(station_id),
  horizon_minutes smallint check (horizon_minutes > 0),
  window_start timestamptz not null,
  window_end timestamptz not null,
  metric_name text not null check (metric_name in ('wape', 'accuracy', 'mae', 'rmse', 'drift')),
  metric_value double precision not null,
  sample_size integer not null check (sample_size >= 0),
  calculated_at timestamptz not null default now(),
  check (window_end >= window_start),
  unique nulls not distinct (
    cycle_id, model_id, station_id, horizon_minutes, window_start, window_end, metric_name
  )
);

create index observations_observed_at_idx on public.observations (observed_at);
create index observations_station_time_desc_idx on public.observations (station_id, observed_at desc);
create index context_observed_at_desc_idx on public.context_observations (observed_at desc);
create index pipeline_runs_started_at_desc_idx on public.pipeline_runs (started_at desc);
create index predictions_target_at_idx on public.predictions (target_at);
create index metrics_calculated_at_desc_idx on public.evaluation_metrics (calculated_at desc);

alter table public.dataset_snapshots enable row level security;
alter table public.stations enable row level security;
alter table public.observations enable row level security;
alter table public.context_observations enable row level security;
alter table public.pipeline_runs enable row level security;
alter table public.model_versions enable row level security;
alter table public.forecast_cycles enable row level security;
alter table public.predictions enable row level security;
alter table public.evaluation_metrics enable row level security;

revoke all on table public.dataset_snapshots from anon, authenticated;
revoke all on table public.stations from anon, authenticated;
revoke all on table public.observations from anon, authenticated;
revoke all on table public.context_observations from anon, authenticated;
revoke all on table public.pipeline_runs from anon, authenticated;
revoke all on table public.model_versions from anon, authenticated;
revoke all on table public.forecast_cycles from anon, authenticated;
revoke all on table public.predictions from anon, authenticated;
revoke all on table public.evaluation_metrics from anon, authenticated;

grant all on table public.dataset_snapshots to service_role;
grant all on table public.stations to service_role;
grant all on table public.observations to service_role;
grant all on table public.context_observations to service_role;
grant all on table public.pipeline_runs to service_role;
grant all on table public.model_versions to service_role;
grant all on table public.forecast_cycles to service_role;
grant all on table public.predictions to service_role;
grant all on table public.evaluation_metrics to service_role;
grant usage, select on all sequences in schema public to service_role;

